"""
Anomaly Report Schema

Defines the structure for anomaly reports generated when invariants
are violated or baseline deviations are detected.

The reasoning layer emits these reports to signal issues with
system coherence (not business correctness).
"""

from enum import Enum
from typing import Dict, Any, Optional
from pydantic import BaseModel, Field


class AnomalySeverity(str, Enum):
    """Severity levels for anomalies."""
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


class AnomalyCategory(str, Enum):
    """Categories of anomalies."""
    INVARIANT_VIOLATION = "INVARIANT_VIOLATION"
    REGRESSION = "REGRESSION"
    INSTABILITY = "INSTABILITY"


class AnomalyEvidence(BaseModel):
    """Evidence supporting the anomaly detection."""
    
    expected: str = Field(
        ...,
        description="What was expected based on invariants or baselines"
    )
    
    observed: str = Field(
        ...,
        description="What was actually observed in the system"
    )
    
    additional_context: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Additional context about the anomaly"
    )


class AnomalyReport(BaseModel):
    """
    Report of a detected anomaly.
    
    Generated by the anomaly detector node when invariants are violated
    or behavior deviates from learned baselines.
    """
    
    severity: AnomalySeverity = Field(
        ...,
        description="Severity of the anomaly"
    )
    
    category: AnomalyCategory = Field(
        ...,
        description="Category of the anomaly"
    )
    
    action_id: Optional[str] = Field(
        default=None,
        description="ID of the action that triggered the anomaly, if applicable"
    )
    
    description: str = Field(
        ...,
        description="Human-readable description of the anomaly",
        min_length=1
    )
    
    evidence: AnomalyEvidence = Field(
        ...,
        description="Evidence supporting this anomaly detection"
    )
    
    timestamp: Optional[str] = Field(
        default=None,
        description="ISO timestamp when anomaly was detected"
    )
    
    class Config:
        json_schema_extra = {
            "example": {
                "severity": "HIGH",
                "category": "INVARIANT_VIOLATION",
                "action_id": "click_submit_button",
                "description": "Action executed but no observable state change occurred",
                "evidence": {
                    "expected": "UI state should change after successful action",
                    "observed": "UI state unchanged after action execution"
                }
            }
        }
